version: '3'
services:
  # === core services ===
  overview-worker:
    image: overview/overview-worker
    volumes:
      - overview-blob-storage:/var/lib/overview/blob-storage
      - overview-searchindex-data:/var/lib/overview/searchindex
    env_file:
      - overview.defaults.env
      - overview.env

  overview-web:
    image: overview/overview-web
    volumes:
      - overview-blob-storage:/var/lib/overview/blob-storage
    env_file:
      - overview.defaults.env
      - overview.env
    networks:
      default:
        aliases:
          - web # TODO make overview-proxy look for overview-web, not web

  # === internal dependencies ===
  overview-database:
    image: overview/overview-database
    volumes:
      - overview-database-data:/var/lib/postgresql/data

  overview-redis:
    image: overview/overview-redis

  # === plugins ===
  overview-plugin-entity-filter:
    image: overview/overview-entity-filter

  overview-plugin-file-browser:
    image: overview/overview-file-browser

  overview-plugin-metadata:
    image: overview/overview-plugin-metadata

  overview-plugin-multi-search:
    image: overview/overview-multi-search

  overview-plugin-word-cloud:
    image: overview/overview-word-cloud

  # === proxy -- which binds them all
  overview-proxy:
    image: overview/overview-proxy
    volumes:
      - overview-acme:/var/lib/acme
    env_file:
      - overview.defaults.env
      - overview.env
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:3000-3010:3000-3010'

volumes:
  overview-acme:
  overview-blob-storage:
  overview-database-data:
  overview-searchindex-data:

networks:
  default:
