version: '3'
services:
  # === core services ===
  overview-worker:
    image: overview/overview-worker:a0dbcf61f0953450fde07f9f8a389b6aa631bef4
    volumes:
      - overview-blob-storage:/var/lib/overview/blob-storage
      - overview-searchindex-data:/var/lib/overview/searchindex
    env_file:
      - overview.defaults.env
      - overview.env

  overview-web:
    image: overview/overview-web:a0dbcf61f0953450fde07f9f8a389b6aa631bef4
    volumes:
      - overview-blob-storage:/var/lib/overview/blob-storage
    env_file:
      - overview.defaults.env
      - overview.env

  # === internal dependencies ===
  overview-database:
    image: overview/overview-database:a0dbcf61f0953450fde07f9f8a389b6aa631bef4
    volumes:
      - overview-database-data:/var/lib/postgresql/data

  overview-db-evolution-applier:
    image: overview/overview-db-evolution-applier:a0dbcf61f0953450fde07f9f8a389b6aa631bef4
    depends_on: [ 'overview-database' ]
    env_file:
      - overview.defaults.env
      - overview.env

  overview-redis:
    image: overview/overview-redis:a0dbcf61f0953450fde07f9f8a389b6aa631bef4

  # === plugins ===
  overview-plugin-entity-filter:
    image: overview/overview-entity-filter:1.0.3

  overview-plugin-file-browser:
    image: overview/overview-file-browser:1.0.3

  overview-plugin-metadata:
    image: overview/overview-plugin-metadata:1.0.3

  overview-plugin-multi-search:
    image: overview/overview-multi-search:1.0.2

  overview-plugin-word-cloud:
    image: overview/overview-word-cloud:1.0.1

  # === proxy -- which binds them all
  overview-proxy:
    image: overview/overview-proxy:latest
    volumes:
      - overview-acme:/var/lib/acme
    env_file:
      - overview.defaults.env
      - overview.env
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:3000-3010:3000-3010'

volumes:
  overview-acme:
  overview-blob-storage:
  overview-database-data:
  overview-searchindex-data:

networks:
  default:
