

overview-blob-storage:
  image: ubuntu:vivid
  container_name: overview-blob-storage
  volumes:
    - /var/lib/overview/blob-storage
  command: /bin/true

documentset-worker:
  image: overview/documentset-worker
  container_name: documentset-worker
  external_links:
    - overview-database
    - overview-messagebroker
    - overview-searchindex
  volumes_from:
    - overview-blob-storage
  restart: on-failure


worker:
  image: overview/worker
  container_name: worker
  external_links:
    - overview-database
    - overview-searchindex
  volumes_from:
    - overview-blob-storage
  restart: on-failure


web:
  image: overview/web
  container_name: web
  external_links:
    - overview-database
    - overview-messagebroker
    - overview-redis
    - overview-searchindex
  volumes_from:
    - overview-blob-storage 
  restart: on-failure
  ports:
    - "9000:9000"

