version: '2'

services:
  overview-word-cloud:
    container_name: overview-word-cloud
    image: overview/overview-word-cloud
    network_mode: "host"
    environment:
      - PORT=3000

  overview-entity-filter:
    container_name: overview-entity-filter
    image: overview/overview-entity-filter
    network_mode: "host"
    environment:
      - PORT=3001

  overview-grep:
    container_name: overview-grep
    image: overview/overview-grep
    network_mode: "host"
    environment:
      - PORT=3002

  overview-file-browser:
    container_name: overview-file-browser
    image: overview/overview-file-browser
    network_mode: "host"
    environment:
      - PORT=3003

  overview-multi-search:
    container_name: overview-multi-search
    image: overview/overview-multi-search
    network_mode: "host"
    environment:
      - PORT=3004
