
overview-database-data:
  image: postgres:9.4
  container_name: overview-database-data
  volumes:
    - /var/lib/postgresql/data
  command: /bin/true

overview-searchindex-data:
  image: elasticsearch:1.7
  container_name: overview-searchindex-data
  volumes:
    - /usr/share/elasticsearch/data
  command: /bin/true

overview-database:
  image: overview/database
  container_name: overview-database
  volumes_from:
    - overview-database-data

messagebroker:
  image: overview/message-broker
  container_name: overview-messagebroker

redis:
  image: redis:2.8
  container_name: overview-redis 

overview-searchindex:
  image: elasticsearch:1.7
  container_name: overview-searchindex
  volumes_from:
    - overview-searchindex-data
  command: elasticsearch \
      -Des.cluster.name="DevSearchIndex" \
      -Des.node.name="SearchIndex" \
      -Des.index.number_of_shards=1 