overview-network:
  container_name: overview-network
  image: busybox
  command: /bin/sleep 99999999d # run forever
  ports:
    - "9000:9000" # overview-web will eventually listen on port 9000

overview-database:
  container_name: overview-database
  image: overview/database
  net: container:overview-network
  volumes_from:
    - overview-database-data

overview-redis:
  container_name: overview-redis 
  net: container:overview-network
  image: redis:2.8

overview-searchindex:
  container_name: overview-searchindex
  image: overview/searchindex
  net: container:overview-network
  volumes_from:
    - overview-searchindex-data
